### ISSUE TITLE
Deprecation of versions

### ISSUE THREAD

**Issue by DentOpt** [ros/joint_state_publisher#100]
We continuously have issues to keep our dockers consistent, because old versions are deprecating. 
E.g. we were using

```
apt install ros-humble-joint-state-publisher=2.3.0-1*
```
which no does not exist anyomore. The only new tag available is 

```
2.4.0-1jammy.20230919.220007
```

If you test/qualify software this is really problematic for industry. 
Would it be possible to maintain older versions with apt?

**Comment by clalancette** [comment]
> Would it be possible to maintain older versions with apt?

We already do via the snapshots repository: https://snapshots.ros.org .  Pick your distribution, and the date you want to pin to, and you can use that going forward.
