### ISSUE TITLE
Issue with use_sim_time.

### ISSUE THREAD

**Issue by rafal-gorecki** [ros/joint_state_publisher#103]
Hello,
I notice when I spawn `robot_state_publisher` and `robot_state_pub_node` with `SetParameter(name="use_sim_time", value="True")`. Nothing is publish on `/joint_states` topic. Any suggestion why is that?

**Comment by sloretz** [comment]
When `use_sim_time` is `True` anything that tries to access time will use the time published on the `/clock` topic. I would expect `joint_state_publisher` to not publish anything when nothing is publishing the time on the `/clock` topic.


Is something publishing time on that topic? Usually the thing publishing time is a simulator like gazebo, or a playback tool like rosbag.
