### ISSUE TITLE
How should Ros2 Jazzy choose a version?

### ISSUE THREAD

**Issue by MickeyCho630** [ros/joint_state_publisher#104]
Which version should I use in Jazzy?

**Comment by DLu** [comment]
`ros2`

**Comment by sloretz** [comment]
@DLu is correct: https://github.com/ros/joint_state_publisher/tree/ros2

If you have the same question about what branch to use for another package, check out the "VCS Version" in the "Repository Summary" for that package on https://index.ros.org .

Example: https://index.ros.org/p/joint_state_publisher/#jazzy

![Screenshot 2024-07-15 11 37 30 AM](https://github.com/user-attachments/assets/7da14395-fd39-4761-9b13-9cd3c6f567f1)
