### ISSUE TITLE
release for dashing and eloquent?

### ISSUE THREAD

**Issue by relffok** [ros/joint_state_publisher#28]
I've just noticed that the joint state publisher is not released for either dashing nor eloquent.
Are there any plans on doing so?

**Comment by clalancette** [comment]
Eventually, yes.  The code was a quick port I did a while ago, and it never worked all that well.  There have been some recent fixes to it (and I'm planning on doing a few more).  Once that is done, and the code has been reviewed, we can do a release into ros2.

**Comment by clalancette** [comment]
This was done last week.  So closing this out.
