### ISSUE TITLE
AttributeError: JointStatePublisher instance has no attribute 'source_update_cb'

### ISSUE THREAD

**Issue by igzubov** [ros/joint_state_publisher#36]
Getting this error on Ubuntu 16.04 and ROS Kinetic:
`[ERROR] [1582565767.970762]: bad callback: <bound method JointStatePublisher.source_cb of <joint_state_publisher.JointStatePublisher instance at 0x7ff0c19dc5a8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/joint_state_publisher/__init__.py", line 202, in source_cb
    if self.source_update_cb is not None:
AttributeError: JointStatePublisher instance has no attribute 'source_update_cb'
`

Why `source_update_cb` is set to None aftrer subscribers are created? Shouldn't this variable be initialized before creating subscribers?

**Comment by sloretz** [comment]
@igzubov thanks for the report! Would you mind trying #41 on your system and reporting if it fixes the issue?

**Comment by igzubov** [comment]
@sloretz tested, fixes.

**Comment by sloretz** [comment]
Thanks @igzubov , closing as fixed by #41 and #43
