### ISSUE TITLE
Available in `eloquent` ?

### ISSUE THREAD

**Issue by comkieffer** [ros/joint_state_publisher#48]
`apt-cache --names-only search joint-state-publisher` only reports packages for dashing. Is a release for eloquent available?

**Comment by clalancette** [comment]
So I did release it for Eloquent, but there hasn't been an Eloquent sync for a while.  This means that joint-state-publisher is available in the testing repository for Eloquent, but not in the main repository.  Luckily, that is going to change later this week: https://discourse.ros.org/t/preparing-for-eloquent-sync-and-patch-release-2020-04-17/13562 .

I'm going to close this, but feel free to reopen if you need more information.

**Comment by comkieffer** [comment]
Awesome, thanks.
