### ISSUE TITLE
joint_state_publisher doesn't work 

### ISSUE THREAD

**Issue by JaehyunShim** [ros/joint_state_publisher#54]
Hi, 

Error code below shows up when testing $ ros2 run joint_state_publisher joint_state_publisher
```sh
# error code
[joint_state_publisher-1]   File "/opt/ros/dashing/lib/python3.6/site-packages/joint_state_publisher/joint_state_publisher.py", line 174, in parse_dependent_joints
[joint_state_publisher-1]     dependent_joints = self.get_parameters_by_prefix('dependent_joints')
[joint_state_publisher-1] AttributeError: 'JointStatePublisher' object has no attribute 'get_parameters_by_prefix'
```
I also tried it with urdf as arguments or with adding some parameters but it still didn't work. 

Thank you in advance,
Ryan

**Comment by clalancette** [comment]
I just fixed this and released it yesterday: #50 .  It will be in the next Dashing sync.
