### ISSUE TITLE
joint_state_publisher  happen error.

### ISSUE THREAD

**Issue by wallEVA96** [ros/joint_state_publisher#61]
sometime joint_state_publisher will happen  error, for example:  UnboundLocalError: local variable 'slider' referenced before assignment in joint_state_publisher on indigo.

**Comment by clalancette** [comment]
Thanks for the report.  We are no longer supporting Indigo as a ROS distribution.  There have been numerous fixes to joint_state_publisher since then, so your options here are to either fix the problems in Indigo yourself, or update to a newer ROS distribution.
