### ISSUE TITLE
JSP colcon build fails [Foxy]

### ISSUE THREAD

**Issue by newcanopies** [ros/joint_state_publisher#62]
Hi, I am not able to build JSP on Foxy/Ubuntu20.04 -- any clues?

joint_state_publisher/joint_state_publisher$ colcon build

```
Starting >>> joint_state_publisher
--- stderr: joint_state_publisher
CMake Error at CMakeLists.txt:4 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.


---
Failed   <<< joint_state_publisher [9.68s, exited with code 1]

Summary: 0 packages finished [10.0s]
  1 package failed: joint_state_publisher
  1 package had stderr output: joint_state_publisher
```

**Comment by sloretz** [comment]
The error message says CMake can't find `catkin`, but `catkin` is only available in ROS 1. Did you check out the the default branch? Checkout the `foxy` branch for building on Foxy instead.

```
git clone https://github.com/ros/joint_state_publisher.git -b foxy
```

You might be interested in the documentation for building ROS Foxy from source: https://docs.ros.org/en/foxy/Installation/Ubuntu-Development-Setup.html

If more issues come up, please ask for help on https://answers.ros.org per the [support guidelines](https://docs.ros.org/en/foxy/Contact.html#support).

**Comment by newcanopies** [comment]
forgot to source Foxy branch 
`$ git checkout foxy`

**Comment by newcanopies** [comment]
thanks @sloretz 
realized this moments ago at viewing: CMakeLists.txt:4 `find_package(catkin REQUIRED)`
