### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by blackhorsewu** [ros/joint_state_publisher#63]
File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 48, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

What can be done?
My Melodic on Ubuntu 18.04 is running python 3.8.5

Victor Wu.

**Comment by clalancette** [comment]
You need to have `python-yaml` installed on your system.  If you are using a pip virtualenv, you need to have it installed in there.

In the future, please ask questions like this on https://answers.ros.org, which is our central question and answer site.  Closing.
