### ISSUE TITLE
Misleading docs for 'zeros' parameter for ROS2

### ISSUE THREAD

**Issue by hello-binit** [ros/joint_state_publisher#65]
Hello, I'm on Ubuntu 20.04, using ROS2 Galactic. Reading the joint_state_publisher [README](https://github.com/ros/joint_state_publisher/blob/ros2/joint_state_publisher/README.md), I'd expect the 'zeros' parameter to take a dictionary, mapping strings to floats. In a ROS2 launch file, I'd expect this to be:

```python
joint_state_publisher_gui_node = Node(
    package='joint_state_publisher_gui',
    executable='joint_state_publisher_gui',
    parameters=[{'zeros': {'joint_lift': 0.2, 'joint_wrist_yaw': 3.4}}]
)
```

The snippet above doesn't work. Looking at the code, 'zeros' is retrieved using the [`get_parameters_by_prefix`](https://github.com/ros/joint_state_publisher/blob/foxy/joint_state_publisher/joint_state_publisher/joint_state_publisher.py#L238) method. So the following snippet works instead:

```python
joint_state_publisher_gui_node = Node(
    package='joint_state_publisher_gui',
    executable='joint_state_publisher_gui',
    parameters=[{'zeros.joint_lift': 0.2, 'zeros.joint_wrist_yaw': 3.4}]
)
```

Let me know if I've misunderstood anything. If it is an issue, happy to file a PR improving the README.

**Comment by clalancette** [comment]
> Let me know if I've misunderstood anything. If it is an issue, happy to file a PR improving the README.

You've understood it perfectly.  I was trying to get this across in this sentence:

```
In Eloquent, pass on the command-line as '-p zeros.joint_name:=value'.
```

But if you think the wording could be further improved, please feel free to open a PR.  I'm happy to review it.

**Comment by DLu** [comment]
Good to close?
