### ISSUE TITLE
Can i move my robot arm like rviz?

### ISSUE THREAD

**Issue by EmadDeve20** [ros/joint_state_publisher#75]
My question sounds confusing I want my robot to move exactly like the robot inside rviz not like your code!
Is this possible? I know I mean badly right now, so let me explain more precisely!

 look at picture in down

![Screenshot from 2021-12-08 12-34-38](https://user-images.githubusercontent.com/60766355/145180052-9ad3e5c3-d18e-433c-bfba-054763e000e1.png)

now look at this picture

![Screenshot from 2021-12-08 12-42-16](https://user-images.githubusercontent.com/60766355/145181210-d22add14-16da-4a6a-bb61-e1d58f9ea289.png)

As you can see, I used your code in the second image, but it was different from the first image! The difference is that I want to shake that orange robot using a code like yours!

I saw your rviz message and your code was no different:

![Screenshot from 2021-12-08 11-31-31](https://user-images.githubusercontent.com/60766355/145181791-5156ec55-d151-45e8-a108-3d700141594a.png)
^ this message from RVIZ

![Screenshot from 2021-12-08 11-32-12](https://user-images.githubusercontent.com/60766355/145181962-7fe5d533-80f4-439e-9e25-8179a5bd2ed3.png)
^ this message from your UI

Is there a way I can shake like a rviz (orange robot) using a slider like your code? Your code is like doing a plan, but I want it before! Is there a way? I'm really confused.

**Comment by clalancette** [comment]
For questions like this, please ask them on https://answers.ros.org, which is our central question and answer site.  You should be able to get some help there.  I'm going to close this one out.

**Comment by EmadDeve20** [comment]
@clalancette Thanks :D
