### ISSUE TITLE
ERROR: cannot launch node of type [joint_state_publisher_gui/joint_state_publisher_gui]

### ISSUE THREAD

**Issue by dvogureckiy99** [ros/joint_state_publisher#90]
I use ros melodic, ubuntu 20.04, Gazebo fortress.

How use this library  ?
I have got error:
```
ERROR: cannot launch node of type [joint_state_publisher_gui/joint_state_publisher_gui]: joint_state_publisher_gui
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/catkin_ws/src/joint_state_publisher/joint_state_publisher
ROS path [2]=/catkin_ws/src/solo12dof_quadruped
ROS path [3]=/catkin_ws/src/solo12dof_solution
ROS path [4]=/opt/ros/melodic/share
```

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
